version: '3.0'
 
services:
   db:
     image: mysql:5.7
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: accountowner
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
     volumes:
       - dbdata:/var/lib/mysql       
     restart: always
 
   accountownerapp:
     depends_on:
       - db
     image: codemazeblog/accountowner:runtime
     build:
       context: .
     ports:
       - "8080:5000"
 
volumes:
    dbdata: